<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Friday 3rd of May 2013 05:28:53 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://www.fotostroek.ru/includes/ha/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"Google" => array ( 
				"enabled" => true,
//				"keys"    => array ( "id" => "914813507632.apps.googleusercontent.com", "secret" => "6-QFSn1nkrEPD1sVrIt5cAcS" )
				"keys"    => array ( "id" => "427206078030-evh9t9op1tghoh18juoethsavujn445s.apps.googleusercontent.com", "secret" => "rZPgs6HVmmsLiJc81PzhI0i3" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "507220212683315", "secret" => "2beb0bcf759e718a74cd2a7145da5265" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "P4CgSeDQCEmnM9W7o7Piiw", "secret" => "5tOs5G9qZ4sOkMt0P7oZt6DKOtcKRypH4QKEXUVZI" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
			"Yandex" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "3b639bb7d53746c39a9be4482a987123", "secret" => "fb583b01b66a4d7390a97275fef59ab5" ) 
			),
			"Mailru" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "704298", "secret" => "724c42ec23b244229230325299ee3849" ) 
			),
			"Odnoklassniki" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "174524672", "secret" => "C507C9526D962B70E12EE26B" /*"secret" => "CBAKAIGLABABABABA" */) 
			),
			"Vkontakte" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "3626310", "secret" => "ChToGU4tcDRL1ISxW8wr" ) 
			)

		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
